# version: '3.8'

networks:
  events-network:
    driver: bridge
    external: true
    
services:
  postgres:
    container_name: pg-events
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
    - events-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: events_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
    - events-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:
